services:
  - type: web
    name: murder-mystery
    runtime: node
    plan: free
    region: frankfurt
    buildCommand: npm install --omit=dev
    startCommand: node server.js
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
